- .gitignore
- README.md
- easy-ui-icons/package.json
- easy-ui-react/package.json
- easy-ui-storybook/package.json
- easy-ui-tokens/package.json
- eslint-config-easy-ui/package.json
- package-lock.json
- package.json
- stylelint-easy-ui/package.json
Sets up the initial, skeleton Easy UI repo structure:
- Initializes as NPM project
- Creates initial workspaces
- Fills out initial README
> Setup initial Easy UI repo structure

- easy-ui-tokens/src/font/base.json
- easy-ui-tokens/src/font/styles.json
- Uses updated typography values per spec from Rachel
- Adjusts the scale to be numeric
- `line_height` uses `rem` instead of unitless values (which are usually preferred) to snap to our pixel grid. recommendations for use in long form copy is TBD
> Update typography tokens

- .github/workflows/chromatic.yml
Only run CI and not automatically publish to Chromatic on dependabot builds. Chromatic can still be manually triggered if needed.
> Skip running chromatic on dependabot pull requests

- easy-ui-react/src/IconButton/IconButton.stories.mdx
react import was added here https://github.com/EasyPost/easy-ui/commit/2d66c4a31d2749ac0ef4a0d4a9287a08c6a86516 and needs to be included in `IconButton` stories file
> adds react import

- documentation/specs/_Template.md
Here's one thought for a component spec template, based on Open UI's component spec template.
I don't want the spec process to be too heavy handed but enough for us to think through potential issues before implementation.
[Open UI Component Spec Template](https://github.com/openui/open-ui/blob/main/site/src/pages/component-spec-template.mdx).
> Create component spec template

- .changeset/fresh-kids-peel.md
- documentation/specs/Button.md
- documentation/specs/DropdownButton.md
- documentation/specs/IconButton.md
- easy-ui-react/src/Button/Button.tsx
- easy-ui-react/src/DropdownButton/DropdownButton.tsx
- easy-ui-react/src/IconButton/IconButton.tsx
- uses `UnstyledButton` in `Button`, `DropdownButton`, and `IconButton` to DRY up code and defer core button logic to the `UnstyledButton` component
> use UnstyledButton in Button, DropdownButton, and IconButton

- .github/workflows/dependabot.yml
Adds auto merging to dependabot workflow after approval. Only runs for non-storybook minor/patch packages. Tested as much as I could using [act](https://github.com/nektos/act) locally.
> Add automerge to dependabot workflow

- .changeset/chilled-meals-whisper.md
- .changeset/pre.json
- easy-ui-icons/CHANGELOG.md
- easy-ui-icons/package.json
- easy-ui-react/CHANGELOG.md
- easy-ui-react/package.json
- easy-ui-tokens/CHANGELOG.md
- easy-ui-tokens/package.json
- Version packages to `-alpha.4`
- make sure you're on latest `main` (`git checkout main && git pull`)
- version the packages (`npm run changes:version`) (this processes all the pending changesets and generates CHANGELOG entries)
- look over the CHANGELOG entries. make sure dev-only packages aren't included (eslint, stylelint, tsconfig, etc). then commit the changes (`git add --all && git commit -m "Version packages"`)
- create a PR (like this one) with the versioned packages commit above. get approval of the PR from team
- merge the PR. re-pull `main`. then publish the packages (`git checkout main && git pull`; `npm run changes: publish`). make sure you have write access to NPM and ensure your registry isn't connected to Cloudsmith, otherwise it'll publish there instead
- `git push …
> Version packages

- easy-ui-react/package.json
- easy-ui-react/vite.config.ts
- package-lock.json
- adds [vite-plugin-react-remove-attributes](https://github.com/l-mbert/vite-plugin-react-remove-attributes) as a dev dep to `easy-ui-react` to remove `data-testid` from prod build
before:
after:
> add plugin to remove test attributes in build

- .changeset/fifty-years-relate.md
- easy-ui-react/src/Tooltip/Tooltip.mdx
- easy-ui-react/src/Tooltip/Tooltip.module.scss
- easy-ui-react/src/Tooltip/Tooltip.stories.tsx
- Per design, set max width for tooltip to `232px`
- Since this is a visual change, no tests were added/modified
- Added tooltip story for long content to show max width
> Add `<Tooltip />` max width

- .changeset/dirty-pillows-love.md
- easy-ui-react/src/TextField/TextField.test.tsx
- easy-ui-react/src/TextField/TextField.tsx
- easy-ui-react/src/Textarea/Textarea.test.tsx
- easy-ui-react/src/Textarea/Textarea.tsx
- Passes properties through to `InputField`. Fixes problem of consumers not having their events registered
- Adds tests for use case
> fix(TextField,Textarea): pass all properties through to InputField

- .github/workflows/release.yml
- adds the release workflow for automatically creating release PRs and then publishing them on merge
- not tested but followed steps outlined in changesets github page. there may be a slight back and forth with getting this to work since it's difficult to test without being added to the mainline
> feat: add release workflow

- .changeset/tidy-pans-lick.md
- easy-ui-react/src/Card/Card.mdx
- easy-ui-react/src/Card/Card.module.scss
- easy-ui-react/src/Card/Card.stories.tsx
- fixes card area not stretching to layouts properly
- adds example story
> fix(Card): card area should behave rules of parent layout

- .changeset/orange-rockets-compare.md
- easy-ui-react/src/Button/_mixins.scss
Adds a color declaration for `<Button variant="filled">` to avoid collisions with `a:hover` element selector rules.
To verify, in Chrome Devtools, this CSS rule was added:
```css
a, a:hover {
color: deeppink;
}
```
Before this PR:
After:
> Set color for hover on `<Button>` with href

- .changeset/small-windows-impress.md
- documentation/specs/Modal.md
- easy-ui-react/src/Modal/Modal.mdx
- easy-ui-react/src/Modal/ModalFooter.tsx
- Passes through `isDisabled` prop to action buttons to support them being disabled
- Adds some documentation to Storybook for this but felt it didn't need a full story or specific unit tests for this change
Note that with Easy UI we're moving to a more constraint-based design for components to promote consistency. That's why we're not blindly allowing any button prop to pass through the actions, because it can lead to unintended Modal styles. So for now we're listing specific props that are allowed to pass through.
> feat(Modal): support disabled actions

- .changeset/silent-beans-try.md
- easy-ui-react/src/Menu/MenuOverlay.tsx
- uses `Overlay` instead of `OverlayContainer` to return focus back to trigger after closing menu. this is per Aria documentation and was simply missed in the implementation
- attempted to write a unit test for this but couldn't get user event, jsdom, and Aria to play nicely together for this change. will come back to it when i figure out how to test focus in these cases
> fix(Menu): return focus to trigger after closing menu

- .changeset/forty-bears-heal.md
- easy-ui-react/src/Modal/Modal.stories.tsx
- easy-ui-react/src/Modal/ModalContainer.tsx
- Adds support for passing in a ReactNode as a ModalContainer children, which allows more lax conditions inside the body of the ModalContainer JSX tag such as multiple boolean conditions. this also lines up more closely with [React Spectrum's implementation](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/dialog/src/DialogContainer.tsx#L33)
> fix(Modal): support ReactNode as ModalContainer children

- easy-ui-react/package.json
- package-lock.json
This reverts commit 3036489a25202fa71a6ea026bc823ad878e8460c.
This version is causing build errors
> Revert "build(deps): Bump overlayscrollbars from 2.3.0 to 2.3.1 (#622)"

- easy-ui-react/package.json
- package-lock.json
Reverts EasyPost/easy-ui#631
again, breaking the build. this time i ignored the dependency
> Revert "build(deps): Bump overlayscrollbars from 2.3.0 to 2.3.1"

- easy-ui-react/package.json
- package-lock.json
This reverts commit 9eef44366f2a7cfa8a86d33b10aecb535308a44e.
> Revert "build(deps): Bump overlayscrollbars from 2.3.0 to 2.3.1 (#636)"

- documentation/specs/ProductLayout.md
- Adds spec for `ProductLayout`
This does not include specs for the more specialized "focused" and "wizard" product layouts. Those will be spec'd in followup work.
_`ProductLayout.Content`:_
_`ProductLayout.TabbedContent`:_
> Create `<ProductLayout />` spec

- .changeset/hot-adults-pretend.md
- easy-ui-react/src/Stepper/Step.module.scss
- easy-ui-react/src/Stepper/StepButton.module.scss
- easy-ui-react/src/Stepper/StepButton.tsx
- use `subtitle1` as font-style instead of two different fonts predicated on state
- clean up margin styles
- confirmed that each `Step` should have a visible focus ring / outline
> Stepper fixes: font, margins, and visible outline

- documentation/specs/VerticalNav.md
- Adds spec for `<VerticalNav />` component
> docs: create `<VerticalNav />` spec

- .changeset/empty-oranges-laugh.md
- documentation/specs/Select.md
- documentation/specs/TextField.md
- documentation/specs/Textarea.md
- easy-ui-react/src/InputField/InputField.module.scss
- easy-ui-react/src/InputField/InputField.tsx
- easy-ui-react/src/InputField/Label.tsx
- easy-ui-react/src/InputField/utilities.ts
- easy-ui-react/src/Select/Select.mdx
- easy-ui-react/src/Select/Select.stories.tsx
- easy-ui-react/src/Select/Select.tsx
- easy-ui-react/src/Select/SelectField.tsx
- easy-ui-react/src/TextField/TextField.mdx
- easy-ui-react/src/TextField/TextField.stories.tsx
- easy-ui-react/src/TextField/TextField.tsx
- easy-ui-react/src/Textarea/Textarea.mdx
- easy-ui-react/src/Textarea/Textarea.stories.tsx
- easy-ui-react/src/Textarea/Textarea.tsx
- replaces `isLabelVisuallyHidden` with `aria-label`.
- `label` is now optional.
- if `label` and `aria-label` are both omitted, a warning is logged to the console.
> replace isLabelVisuallyHidden with aria-label

- .changeset/weak-rivers-check.md
- easy-ui-icons/src/Download.json
- easy-ui-icons/src/Receipt.json
Adding the Download and Receipt icons that are used on the shipments page
> Adds the Download and Receipt icons

- .changeset/six-turkeys-speak.md
- easy-ui-react/src/DataGrid/Cell.tsx
- easy-ui-react/src/DataGrid/ColumnHeader.tsx
- easy-ui-react/src/DataGrid/DataGrid.stories.tsx
- easy-ui-react/src/DataGrid/DataGrid.test.tsx
- fix DataGrid using row count instead of column count to track where columns were in the table
- Adds story and test
Bug is causing gaps in tables with 1 row:
> fix(DataGrid): track action columns correctly

- .changeset/heavy-crabs-hunt.md
- easy-ui-react/src/SearchNav/SearchNav.test.tsx
- easy-ui-react/src/Stepper/Stepper.tsx
- easy-ui-react/src/utilities/test.ts
- cleans up test noise
- uses correct alignment prop on Stepper
- silences console errors on tests that throw
clean test output:
> fix: clean up test noise

- .changeset/thirty-guests-exist.md
- easy-ui-react/src/DataGrid/Cell.module.scss
- easy-ui-react/src/DataGrid/ColumnHeader.module.scss
- easy-ui-react/src/DataGrid/DataGrid.module.scss
- on the DataGrid, when there are no rows and `rowExpansion` is enabled, there is a gap between the first two columns due to not having content in its column. this fixes that
Before:
After:
> fix(DataGrid): close column gap in some edge cases

- .changeset/mean-pants-smile.md
- easy-ui-react/src/SearchNav/CondensedSearchNav.tsx
- easy-ui-react/src/SearchNav/SearchNav.mdx
- easy-ui-react/src/SearchNav/SearchNav.module.scss
- easy-ui-react/src/SearchNav/SearchNav.stories.tsx
- easy-ui-react/src/SearchNav/SearchNav.tsx
- easy-ui-react/src/SearchNav/context.ts
Makes a couple updates to support updated docs designs where the logo group is preserved on small screens:
- Adds `condensedBehavior` prop to allow for preserving the logo on small screens
- Adjusts horizontal padding to be `24px` on small screens too
```
<SearchNav condensedBehavior="preserve-logo">
{/* etc */}
</SearchNav>
```
_Unable to add specific unit test due to jsdom limitations around a media query related behavior._
> feat(SearchNav): add condensedBehavior prop

- .changeset/tall-dragons-laugh.md
- documentation/specs/CodeBlock.md
- easy-ui-react/src/CodeBlock/CodeBlock.stories.tsx
- easy-ui-react/src/CodeBlock/CodeBlock.test.tsx
- easy-ui-react/src/CodeBlock/CodeBlock.tsx
- Allows hiding the copy button for text that doesn't make sense to copy
> feat(CodeBlock): support hiding copy button

- .changeset/hungry-avocados-jump.md
- easy-ui-react/src/CodeSnippet/SyntaxHighlighter.tsx
- easy-ui-react/src/CodeSnippet/theme.ts
- Disables automatic Prism highlighting on page load, which can trigger hydration errors in react and flash of unstyled content on our code blocks
- Adjusts theme to ensure line clamping works correctly on initial load
> patch(CodeSnippet): disable automatic prism highlighting

- .changeset/chilly-spies-cheer.md
- easy-ui-react/src/CodeBlock/CodeBlock.module.scss
- easy-ui-react/src/CodeBlock/CodeBlock.tsx
- fixes the scenario where CodeBlock headers don't always collapse with long titles due to invalid flex positioning
before:
after:
> fix(CodeBlock): header title should support collapsing

- .changeset/tricky-kids-fix.md
- easy-ui-react/src/Tooltip/Tooltip.module.scss
- Fixes a case where react-aria's tooltip positioning logic would apply both `bottom` and `top` measurements at the edge of the screen
> fix(CodeBlock): add min height to tooltip

- .changeset/quiet-singers-switch.md
- easy-ui-react/README.md
- easy-ui-react/vite.config.mts
- Remove `@react-aria/ssr` from being embedded in the build to allow for apps to have a singleton instance of `SSRProvider`. Addresses `When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.` warnings.
> fix: exclude SSRProvider from build

- package-lock.json
- package.json
Fixes typescript version warning:
_Not applicable to change._
> fix: typescript version for lint warning

- .changeset/quick-bobcats-wait.md
- documentation/specs/Card.md
- easy-ui-react/src/Card/Card.mdx
- easy-ui-react/src/Card/Card.module.scss
- easy-ui-react/src/Card/Card.stories.tsx
- easy-ui-react/src/Card/Card.test.tsx
- easy-ui-react/src/Card/Card.tsx
- easy-ui-react/src/types.ts
- easy-ui-react/src/utilities/storybook.tsx
- easy-ui-tokens/src/shadow/base.json
- Add support for box shadows with `<Card boxShadow="1" />` per the shadow levels outlined in Figma design spec
- Fix `background` types
[Link to Story](https://63f50c7c86f6514d2e0ef4be-edphtsadgo.chromatic.com/?path=/story/components-card--shadow).
> feat(Card): support box shadow

- .changeset/clean-pugs-provide.md
- .changeset/nervous-goats-mate.md
- documentation/specs/DataGrid.md
- easy-ui-react/src/DataGrid/ActionsCellContent.module.scss
- easy-ui-react/src/DataGrid/ActionsCellContent.tsx
- easy-ui-react/src/DataGrid/Cell.module.scss
- easy-ui-react/src/DataGrid/Cell.tsx
- easy-ui-react/src/DataGrid/ColumnHeader.module.scss
- easy-ui-react/src/DataGrid/ColumnHeader.tsx
- easy-ui-react/src/DataGrid/DataGrid.mdx
- easy-ui-react/src/DataGrid/DataGrid.module.scss
- easy-ui-react/src/DataGrid/DataGrid.stories.tsx
- easy-ui-react/src/DataGrid/DataGrid.test.tsx
- easy-ui-react/src/DataGrid/ExpandedRowContent.module.scss
- easy-ui-react/src/DataGrid/ExpandedRowContent.tsx
- easy-ui-react/src/DataGrid/HeaderRow.tsx
- easy-ui-react/src/DataGrid/Row.module.scss
- easy-ui-react/src/DataGrid/Row.tsx
- easy-ui-react/src/DataGrid/SortIndicator.module.scss
- easy-ui-react/src/DataGrid/Table.tsx
- easy-ui-react/src/DataGrid/UnstyledPressButton.tsx
- easy-ui-react/src/DataGrid/constants.ts
- easy-ui-react/src/DataGrid/context.ts
- easy-ui-react/src/DataGrid/types.d.ts
- easy-ui-react/src/DataGrid/useExpandedRow.ts
- Adds new header variant and changes primary variant color
- Refactors to `table` HTML to support React Aria's clicking rows
- Removes `templateColumns` with move to built-in `table` layout
- Adds `size` prop—supporting `sm`, `md` (default), `lg`
- Various style and bug fixes
[Link to story](https://update-datagrid-header-color--63f50c7c86f6514d2e0ef4be.chromatic.com/?path=/docs/components-datagrid--docs).
> feat(DataGrid): add size, header variant, row click, and new colors

- .changeset/loud-penguins-kiss.md
- documentation/specs/Card.md
- easy-ui-react/src/Card/Card.mdx
- easy-ui-react/src/Card/Card.module.scss
- easy-ui-react/src/Card/Card.stories.tsx
- easy-ui-react/src/Card/Card.test.tsx
- easy-ui-react/src/Card/Card.tsx
- easy-ui-react/src/ToggleCard/ToggleCard.module.scss
- easy-ui-react/src/ToggleCard/ToggleCard.tsx
- easy-ui-react/src/types.ts
- easy-ui-react/src/utilities/storybook.tsx
`<Card />`:
- Add support for `borderRadius` that maps to `shape.border_radius` values
- Add support for `paddingY` and `paddingX`; values map to spacing tokens or an object of spacing tokens for different screen sizes
`<ToggleCard />`:
- Uses new `<Card />` props to update component to match Figma designs
> feat: support new `Card` props and update `ToggleCard` to use new props

- .changeset/khaki-pumas-deliver.md
- documentation/specs/DataGrid.md
- easy-ui-react/src/DataGrid/Cell.module.scss
- easy-ui-react/src/DataGrid/Cell.tsx
- easy-ui-react/src/DataGrid/DataGrid.mdx
- easy-ui-react/src/DataGrid/DataGrid.stories.tsx
- easy-ui-react/src/DataGrid/DataGrid.test.tsx
- easy-ui-react/src/DataGrid/Row.tsx
- easy-ui-react/src/DataGrid/Table.tsx
- easy-ui-react/src/DataGrid/types.d.ts
> T79379 data grid empty state

- .changeset/short-hats-mate.md
- easy-ui-react/src/NexusLayout/NexusLayout.stories.tsx
- easy-ui-react/src/NexusLayout/NexusLayoutMultipage.module.scss
> fix: overflow for NexusLayoutMultipageContent

- .github/workflows/chromatic.yml
- .github/workflows/release.yml
**context:**
https://github.com/EasyPost/easy-ui/actions/runs/11845921295/job/33012393926?pr=1467
starting yesterday a couple of our workflows (chromatic and release) started failing and it looks to be due to permission issues. i reached out to dev tools on slack to ask if anything changed recently in the easypost github org settings / permissions that could prevent `github-actions[bot]` from doing things, but havent heard back yet.
> T82577: update workflow permissions

- .changeset/heavy-yaks-destroy.md
- easy-ui-react/src/EmptyStateCard/EmptyStateCard.tsx
- Updates EmptyStateCard to use `solid` variant by default
- Support custom extension via `cardProps`
This matches the Figma which doesn't have a border:
> fix: EmptyStateCard use solid variant

- .changeset/unlucky-grapes-joke.md
- easy-ui-react/vite.config.mts
- package-lock.json
- upgrading Vite renamed the default filename for the CSS file. this fixes it
> fix: css output filename

- easy-ui-react/src/Menu/Menu.module.scss
- easy-ui-react/src/Menu/Menu.stories.tsx
- easy-ui-react/src/Menu/Menu.test.tsx
- easy-ui-react/src/Menu/MenuItem.tsx
- easy-ui-react/src/Menu/MenuOverlay.tsx
- easy-ui-react/src/Menu/MenuSection.tsx
- easy-ui-react/src/Menu/utilities.ts
- example of react aria menu compatible selection
- other menu fixes
Link to Story:
https://menu-adjustment--63f50c7c86f6514d2e0ef4be.chromatic.com/?path=/story/components-menu--multiple-selection-with-select-all
View "Actions" panel to see how behavior reflects what is expected for React Aria selection. When selecting a list of items the returned keys are an array of items. When selecting "Select all" directly, the key returned is "all". This matches what is outlined here: https://react-spectrum.adobe.com/react-aria/selection.html#select-all
We'll also want to update the docs to note this.
> react aria compatible menu selection

- .changeset/selfish-mice-reflect.md
- easy-ui-react/src/Select/SelectOverlay.tsx
- easy-ui-react/src/Tooltip/Tooltip.tsx
- Tooltips and Selects were using OverlayContainer instead of Overlay which was causing them not to work right in modals and drawers
> feat(Menu,Select): use proper Overlay primitive

- .changeset/slimy-trees-peel.md
- easy-ui-react/src/Calendar/Calendar.stories.tsx
- easy-ui-react/src/Calendar/Calendar.tsx
- easy-ui-react/src/Calendar/CalendarBase.tsx
- easy-ui-react/src/Calendar/CalendarCell.module.scss
- easy-ui-react/src/Calendar/CalendarCell.tsx
- easy-ui-react/src/Calendar/CalendarGrid.tsx
- easy-ui-react/src/Calendar/CalendarHeader.tsx
- easy-ui-react/src/RangeCalendar/RangeCalendar.mdx
- easy-ui-react/src/RangeCalendar/RangeCalendar.stories.tsx
- easy-ui-react/src/RangeCalendar/RangeCalendar.test.tsx
- easy-ui-react/src/RangeCalendar/RangeCalendar.tsx
- easy-ui-react/src/RangeCalendar/index.ts
- Refactor <Calendar /> 
- Create <RangeCalendar />
> feat: RangeCalendar and refactor Calendar

- .changeset/rotten-tips-divide.md
- easy-ui-react/src/DataGrid/Cell.module.scss
- In cases where the actions cell is expanded beyond its content width, align it toward the end 
before:
after:
> fix(DataGrid): align actions menu to end

- .changeset/smooth-toys-joke.md
- easy-ui-icons/src/OpenInNew.json
> feat: add open_in_new icon

- .changeset/short-shrimps-beg.md
- easy-ui-react/src/InputField/InputField.module.scss
- support clicking through icons that overlay Select and TextField
this fixes the bug particularly noticeable on Select components where users can't open the dropdown when their mouse is over the arrow icon. preserves actionable icon such as in password textfield
> fix(Select,TextField): click through icon

- .changeset/short-lizards-promise.md
- easy-ui-react/src/DataGrid/DataGrid.module.scss
- easy-ui-react/src/DataGrid/Row.module.scss
- easy-ui-react/src/DataGrid/Row.tsx
- easy-ui-react/src/DataGrid/Table.tsx
- easy-ui-react/src/DataGrid/VisuallyHiddenCellContent.tsx
- easy-ui-react/src/DataGrid/context.ts
- supports user selection when possible. still can't select text when DataGrid is in selection mode or if a row can be clicked. this is because React Aria intercepts events for each
- unbreaks line-height by removing the line-height declaration on the parent and solving the height issue elsewhere
> fix(DataGrid): support user selection and unbreak line-height

- .changeset/forty-crabs-invent.md
- easy-ui-react/src/Text/Text.module.scss
- easy-ui-react/src/Text/Text.stories.tsx
- easy-ui-react/src/Text/Text.test.tsx
- easy-ui-react/src/Text/Text.tsx
- support the `whiteSpace` prop on `Text`
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
> feat(Text): whiteSpace

- .changeset/brown-cheetahs-design.md
- easy-ui-react/src/Checkbox/Checkbox.stories.tsx
- easy-ui-react/src/styles/_accessibility.scss
- fixes our checkboxes, radios, and toggles to allow links and buttons to be clickable inside of their labels. this would support our use case on the sign up page, for instance, that includes terms and privacy links
> fix(Checkbox,RadioGroupItem,Toggle): support clickable elements in text

- .changeset/brown-buckets-whisper.md
- easy-ui-react/src/Button/Button.test.tsx
- easy-ui-react/src/Button/Button.tsx
- remove support for overwriting `className` on `Button`
`<Button className="extend" />` overwrites button styles by accidentally spreading props at the end. this is a pretty big departure from Easy UI's current expectations that presentational components contain their styles and provide extensions only through props, and can cause further breaking changes later with a harder upgrade path
🚨 this is technically a breaking change but due to being in pre-release mode, it's better served as a patch. we will need to update 4 instances in our products. these can be found with this `<Button([\s\n\r]+|[^>]+)className` regex 🚨 
~Strikethrough~ any items that are not applicable to …
> fix(Button): remove support for className

- .changeset/thirty-cougars-warn.md
- easy-ui-react/src/DataGrid/Row.module.scss
- set row line-height to 0 to fix extra spacing bleeding around cells in a row
previously we had `line-height: 0` set on the `DataGrid` element which caused problems with content in the expanded row. to correct this, we removed `line-height`, but this introduced a nonobvious bug with cell content that didn't contain inline elements (including empty cells).
this sets `line-height` back on the row to fix extra space bleeding out of the cells while not reintroducing the previous bug. content cells also have line height specified so this won't break wrapping text inside of a cell.
before:
after:
> fix(DataGrid): extra spacing inside rows

- .changeset/chilly-mugs-hunt.md
- easy-ui-react/src/KebabButton/KebabButton.tsx
There is currently an issue in prod where on safari the kebab menu on data grids do not work.
This just swaps out the `UnstyledPressButton` for `UnstyledButton` in the kebab for the datagrid's kebab menu. Not sure why that fixes it, but Steve suggested it and it does in fact fix it.
> Fix: Fixes the DataGrid kebab button on safari

- .changeset/green-chefs-retire.md
- easy-ui-react/src/DataGrid/types.ts
Currently there are no types for the data grid component because the typedefs are in a `.d.ts` file. This changes it to a `.ts` file. I checked by installing the built package in another next app, and this fixes the types on the datagrid
> Datagrid types fix

- .changeset/fresh-phones-talk.md
- easy-ui-react/src/Notification/Notification.module.scss
- easy-ui-react/src/Notification/Notification.tsx
- Fixes `Notification` to be closer to most up-to-date Figma spec
- Also fixes an issue where the close button styles were sometimes colliding with the UnstyledButton styles due to CSS build order. (i.e. .closeButton was included before the .unstyledButton class in the styles.css file). fix is to separate the colliding styles into their own element. we may want to look into this for other situations
add bottom border radius and 48px side margin:
per Figma:
> fix(Notification): border radius, margin, close button

- .changeset/tall-paths-reply.md
- easy-ui-react/src/DataGrid/DataGrid.tsx
- easy-ui-react/src/DataGrid/Table.tsx
- easy-ui-react/src/DataGrid/types.ts
- package-lock.json
- Makes the Columns and Rows types mutually exclusive
- Makes the `Key` types generic, and based on the `key` property of the column/row its referring to
- Makes the sort descriptor type `key` aware
I went and checked all the instances of DataGrid in TS files, and these changes allow us to get rid of all the `ts-expect-error` comments
> Fix Datagrid Types

- .changeset/green-horses-trade.md
- easy-ui-react/src/Text/Text.module.scss
- easy-ui-react/src/Text/Text.stories.tsx
- easy-ui-react/src/Text/Text.test.tsx
- easy-ui-react/src/Text/Text.tsx
- Adds `textWrap` prop to `Text` component: https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap
Specifically, found need in product for specifying `text-wrap: balance`.
- ~[ ] TSDoc is written for any API surface area~
- ~[ ] Specs are up-to-date~
> feat(Text): add `text-wrap` support via `textWrap` prop

- .changeset/spicy-moments-mate.md
- easy-ui-react/src/RadioGroup/RadioGroup.stories.tsx
- easy-ui-react/src/RadioGroup/RadioGroup.tsx
- easy-ui-react/src/Select/Select.stories.tsx
- easy-ui-react/src/Select/Select.tsx
This opens the `Select` and `RadioGroup` component's keys to be generic instead just the `Key = string | number` loose type. I checked in EPWA and this seems to work as expected.
Unfortunately react-aria isn't super happy with these changes, as it wants the keys to be of type `Key`. I added a type case for the props being passed to react aria stuff :/ not ideal, but open to suggestions if we don't want that...
> Makes the select and radiogroup components take generic keys

- .changeset/pink-paths-film.md
- easy-ui-react/src/Modal/Modal.module.scss
React Aria hides the modal for any subcomponent popover, which meant it was hiding for certain dropdowns. So for now, revert the hiding, but keep the nesting allowance.
Will figure out alternative approach for presentation.
> fix(Modal): disable hiding parent of nested modal

- .changeset/polite-months-rule.md
- easy-ui-react/src/Text/Text.tsx
- easy-ui-react/src/Typography.mdx
- easy-ui-react/src/styles/_typography.scss
- easy-ui-tokens/src/font/styles.json
Instead of setting a font family explicitly it should inherit the root font family so that it can pick up font families on the theme.
> fix(Text): inherit theme font family
