EasyPost/easy-ui

- .editorconfig
- .eslintignore
- .eslintrc.js
- .gitignore
- .prettierignore
- .prettierrc
- .stylelintignore
- .stylelintrc.js
- .vscode/extensions.json
- README.md
- easy-ui-react/tsconfig.json
- easy-ui-tsconfig/base.json
- easy-ui-tsconfig/dom.json
- easy-ui-tsconfig/library.json
- easy-ui-tsconfig/package.json
- eslint-config-easy-ui/index.js
- eslint-config-easy-ui/package.json
- package-lock.json
- package.json
- stylelint-easy-ui/index.js
- stylelint-easy-ui/package.json
- tsconfig.json
- turbo.json
Adds skeletons for the following tools:
These are only a starting point and will need to be adjusted as we further implement the library.
> Add initial tooling

- README.md
on a previous PR where i added the contribution info, i added the wrong path
> fix(readme): contribution link

- package-lock.json
When trying to setup this repo, upon running `npm install`, I was seeing the following error:
```
npm ERR! code 1
npm ERR! path /Users/laura/Development/playground/easy-ui/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! [turbo] Failed to find package "turbo-darwin-64" on the file system
npm ERR!
npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
npm ERR! package.json feature is used by turbo to install the correct binary executable
npm ERR! for your current platform. This install script will now attempt to work around
npm ERR! this. If that fails, you need to remove the "--no-optional" flag to use turbo.
npm ERR!
npm ERR! node:internal/modules/cjs/loader:933
npm ERR!   const err = new Error(message);
npm ERR! …
```
> Adds turborepo optional deps

- .github/workflows/chromatic.yml
- README.md
- easy-ui-icons/README.md
- easy-ui-icons/package.json
- easy-ui-icons/src/CheckCircle.json
- easy-ui-icons/src/DocumentScanner.json
- easy-ui-icons/src/Error.json
- easy-ui-icons/src/Warning.json
- easy-ui-react/README.md
- easy-ui-react/package.json
- easy-ui-react/src/components/Placeholder/Placeholder.module.css
- easy-ui-react/src/components/Placeholder/Placeholder.module.scss
- easy-ui-react/src/components/Placeholder/Placeholder.stories.mdx
- easy-ui-react/src/components/Placeholder/Placeholder.test.tsx
- easy-ui-react/src/components/Placeholder/Placeholder.tsx
- easy-ui-react/src/styles/_common.scss
- easy-ui-react/src/test/setup.ts
- easy-ui-react/src/utilities/css.ts
- easy-ui-tokens/README.md
- easy-ui-tokens/config.js
- easy-ui-tokens/package.json
- easy-ui-tsconfig/base.json
- easy-ui-tsconfig/definitions/styles.d.ts
- package-lock.json
- package.json
- turbo.json
- vite.config.ts
Adds (updates) the Placeholder component to exercise the infrastructure.
- Utilizes tokens
- Utilizes icons (updates icon package export config)
- Updates TypeScript config to use `node16` module resolution
- Add SCSS support
- Adds Vitest
- Update turbo
- Remove unused icons and add used icons
- Update READMEs
- Add Chromatic workflow
> Add Placeholder component

- documentation/specs/Button.md
- documentation/specs/DropdownButton.md
- documentation/specs/Icon.md
- documentation/specs/IconButton.md
- documentation/specs/Text.md
- documentation/specs/Theme.md
- documentation/specs/_Template.md
- Updates Text spec with new format (whatever sections relevant)
- Update other specs with bare minimum structure
- Update template with minor changes
> Update Text spec with new format

- documentation/specs/Banner.md
- adds spec for upcoming `Banner` component
> banner spec

- documentation/decisions/011_unstyled_button.md
- adds decision record for supporting an internal `UnstyledButton` component
> decision record for unstyled button

- .changeset/ten-toes-grin.md
- easy-ui-react/src/Button/Button.test.tsx
- easy-ui-react/src/DropdownButton/DropdownButton.test.tsx
- easy-ui-react/src/IconButton/IconButton.test.tsx
- easy-ui-react/src/UnstyledButton/UnstyledButton.test.tsx
- easy-ui-react/src/UnstyledButton/UnstyledButton.tsx
- easy-ui-react/src/UnstyledButton/index.ts
Creates `UnstyledButton` component
> creates unstyledbutton

- .github/workflows/dependabot-approval.yml
Based on: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request
> Add automated dependabot approval

- documentation/specs/TextField.md
> textfield spec

- .github/pull_request_template.md
Update PR template with item for accessibility violations.
> Add accessibility item to pull_request_template.md

- .changeset/pre.json
- easy-ui-icons/CHANGELOG.md
- easy-ui-icons/package.json
- easy-ui-react/CHANGELOG.md
- easy-ui-react/package.json
- easy-ui-tokens/CHANGELOG.md
- easy-ui-tokens/package.json
Bumps our `alpha` to the next version by running `npm run changes:version`.
> Version packages

- documentation/specs/Checkbox.md
> Create `<Checkbox />` spec

- documentation/specs/Toggle.md
> Create `<Toggle />` spec

- documentation/specs/RadioGroup.md
> Create `<RadioGroup />` spec

- easy-ui-react/vite.config.ts
vitest changed its auto include behavior requiring excluding our utilities/test.ts file
> Fix vitest

- documentation/specs/CodeBlock.md
> Create `<CodeBlock />` spec

- easy-ui-react/src/Button/Button.tsx
- easy-ui-react/src/DropdownButton/DropdownButton.tsx
- easy-ui-react/src/Icon/Icon.tsx
- easy-ui-react/src/IconButton/IconButton.tsx
- Adds basic tsdocs for `<Button />`, `<IconButton />`, `<DropdownButton />`, and `<Icon />`
> docs for Button, IconButton, DropdownButton, and Icon

- .changeset/polite-socks-crash.md
- easy-ui-icons/src/AddCard.json
- easy-ui-icons/src/Alarm.json
- easy-ui-icons/src/Article.json
- easy-ui-icons/src/Cycle.json
- easy-ui-icons/src/FilterAlt.json
- easy-ui-icons/src/FilterAltOff.json
Adds "cycle", "add_card", "alarm", "filter_alt", "filter_alt_off", and "article" icons
> Adds more icons

- .changeset/two-poets-drop.md
- easy-ui-icons/src/ArrowDropDown.json
- easy-ui-icons/src/ArrowDropUp.json
Adds "arrow_drop_up" and "arrow_drop_down" icons
> Add arrow_drop_up and arrow_drop_down icons

- documentation/specs/Modal.md
> Add `<Modal />` spec

- .changeset/six-hairs-greet.md
- easy-ui-icons/src/History.json
> Adds history icon

- .changeset/little-colts-whisper.md
- easy-ui-icons/src/Link.json
> Add Link icon

- .changeset/strange-icons-arrive.md
- easy-ui-react/src/Modal/Modal.mdx
- easy-ui-react/src/Modal/ModalFooter.tsx
- adds support for passing color to actions. i missed this spec requirement in the implementation phase
> feat(Modal): support passing color to actions

- .changeset/small-keys-peel.md
- easy-ui-icons/src/CodeBlocks.json
- easy-ui-icons/src/CollectionsBookmark.json
- easy-ui-icons/src/LocalShipping.json
- easy-ui-icons/src/MenuBook.json
- easy-ui-icons/src/Radar.json
Add "menu_book", "local_shipping", "code_blocks", "collections_bookmark", and "radar" icons
> Add five icons

- easy-ui-react/package.json
- package-lock.json
Reverts EasyPost/easy-ui#629
breaking the build
> Revert "build(deps): Bump @types/react from 18.2.21 to 18.2.22"

- documentation/specs/TabPanels.md
> Create `<TabPanels />` spec

- documentation/specs/Stepper.md
> Create `<Stepper />` spec

- .changeset/shy-mayflies-divide.md
- easy-ui-icons/src/MoreVert600.json
> Adds MoreVert600 Icon

- documentation/specs/SearchNav.md
- creates spec for `<SearchNav />` component
> Create `<SearchNav />` spec

- easy-ui-react/src/DataGrid/DataGrid.stories.tsx
- Adds example of data grid that uses icons in cell
> Add icon example to data grid

- .changeset/happy-pens-press.md
- easy-ui-icons/src/ArrowForward.json
> Add ArrowForward Icon

- .changeset/three-bulldogs-eat.md
- easy-ui-react/src/Button/_mixins.scss
- easy-ui-react/src/CodeBlock/LanguageMenu.module.scss
- easy-ui-react/src/CodeBlock/LanguageMenu.tsx
- easy-ui-react/src/InputField/InputField.module.scss
- easy-ui-react/src/Notification/Notification.module.scss
- easy-ui-react/src/ProductLayout/HelpMenu.module.scss
- easy-ui-react/src/ProductLayout/ProductLayoutHeader.module.scss
- easy-ui-react/src/SearchNav/CTAGroup.module.scss
- easy-ui-react/src/SearchNav/CondensedSearchNav.module.scss
- easy-ui-react/src/SearchNav/SecondaryCTAItem.module.scss
- easy-ui-react/src/SearchNav/SelectorTrigger.module.scss
- easy-ui-react/src/Stepper/StepButton.module.scss
- easy-ui-react/src/UnstyledButton/UnstyledButton.module.scss
- easy-ui-react/src/UnstyledButton/UnstyledButton.test.tsx
- easy-ui-react/src/UnstyledButton/UnstyledButton.tsx
- support base styles for` UnstyledButton`
- update styles for Easy UI components that use `UnstyledButton`
> feat: support base styles for UnstyledButton

- documentation/specs/FormLayout.md
> docs: create `<FormLayout />` spec

- easy-ui-react/src/Checkbox/Checkbox.tsx
- easy-ui-react/src/InputField/InputField.tsx
- easy-ui-react/src/InputField/Label.tsx
- easy-ui-react/src/RadioGroup/RadioGroupItem.tsx
- easy-ui-react/src/Theme/Theme.tsx
- easy-ui-react/src/types.ts
- runs `npm run format` and preserves changes in `easy-ui-react`
> prettier format

- package-lock.json
- package.json
- upgrades changesets to fix bug with release
> fix: upgrade changesets to fix release bug

- .changeset/light-dryers-approve.md
- easy-ui-icons/src/Eco.json
> Adds eco icon

- .changeset/silly-otters-pump.md
- easy-ui-react/src/Checkbox/Checkbox.tsx
- easy-ui-react/src/Toggle/Toggle.tsx
- easy-ui-react/src/Tooltip/Tooltip.stories.tsx
- Forward refs for checkbox and toggle so that tooltips can be attached to them
- Add examples of tooltip attached in storybook
> fix(Checkbox,Toggle): forward refs

- .changeset/gold-walls-fold.md
- easy-ui-icons/src/Barcode.json
- easy-ui-icons/src/Package2.json
- easy-ui-icons/src/Schedule.json
- easy-ui-icons/src/ThumbUp.json
There are some icons in the current theme1 and theme2 for tracking web that are not in easy-ui-icons. This adds those icons
> Adds Barcode, Package2, Schedule, and ThumbUp Icons

- .changeset/thin-laws-dance.md
- easy-ui-icons/src/Tune.json
> adds tune icon

- .changeset/stupid-coins-smile.md
- easy-ui-icons/src/ChevronRight400.json
Add Chevron right weight 400 icon
> add chevron right weight 400 icon

- .changeset/giant-students-attack.md
- easy-ui-react/src/Card/Card.module.scss
- easy-ui-react/src/Card/Card.tsx
- adds neutral status to card component
> feat: add neutral status to card component

- .changeset/five-humans-battle.md
- easy-ui-icons/src/Package.json
Please provide a brief summary of the changes made and why they were made.
Include any notes, screenshots, or videos that may be helpful for developers reviewing this pull request.
> add package icon

- .changeset/silver-avocados-share.md
- easy-ui-icons/src/Schema.json
> add schema icon

- .changeset/polite-suns-brush.md
- easy-ui-icons/src/Settings.json
> add settings icon

- .changeset/tiny-paws-kick.md
- .storybook/public/poppins.css
- documentation/decisions/013_docs_content_styleguide.md
- documentation/specs/Calendar.md
- easy-ui-icons/src/KeyboardDoubleArrowLeft.json
- easy-ui-icons/src/KeyboardDoubleArrowRight.json
- easy-ui-icons/src/Receipt.json
- easy-ui-react/src/Calendar/Calendar.mdx
- easy-ui-react/src/Calendar/Calendar.module.scss
- easy-ui-react/src/Calendar/Calendar.stories.tsx
- easy-ui-react/src/Calendar/Calendar.test.tsx
- easy-ui-react/src/Calendar/Calendar.tsx
- easy-ui-react/src/Calendar/CalendarCell.module.scss
- easy-ui-react/src/Calendar/CalendarCell.tsx
- easy-ui-react/src/Calendar/CalendarGrid.module.scss
- easy-ui-react/src/Calendar/CalendarGrid.tsx
- easy-ui-react/src/Calendar/CalendarHeader.module.scss
- easy-ui-react/src/Calendar/CalendarHeader.tsx
- easy-ui-react/src/Calendar/index.ts
- tsconfig.json
Create `<Calendar />` component
> Calendar component

- .changeset/blue-shirts-beam.md
- easy-ui-icons/src/AttachMoney.json
> Add attach money icon

- .changeset/shy-zebras-bathe.md
- easy-ui-react/src/Calendar/Calendar.test.tsx
**Issue:**
Assert value is outside of the month` <Calendar />` rendered
**Solution:**
Update assert value to regex instead of static value
> Fix Calendar component unit test

- .changeset/wet-days-chew.md
- easy-ui-icons/src/CalendarAddOn.json
> Add calendar add on icon

- .github/pull_request_template.md
Update the PR template based on learnings from a year of Easy UI development and sync with what is in KB article.
_Not applicable to this change._
> fix: update PR template

- easy-ui-react/src/Calendar/Calendar.stories.tsx
Fixes story name console warning:
_Not applicable to change._
> fix(Calendar): story name warning

- easy-ui-react/src/CodeBlock/CodeBlock.test.tsx
Fixes the following test console warning:
_Not applicable to change._
> fix(CodeBlock): test warning

- documentation/specs/Pill.md
- adds spec for supporting a `Pill` component
> spec: Pill component

- documentation/specs/SplitToggleCard.md
Add spec for `SplitToggleCard` component
> SplitToggleCard spec

- .changeset/polite-lamps-shop.md
- easy-ui-react/src/Card/Card.stories.tsx
- easy-ui-react/src/SplitToggleCard/SplitToggleCard.mdx
- easy-ui-react/src/SplitToggleCard/SplitToggleCard.stories.tsx
- easy-ui-react/src/SplitToggleCard/SplitToggleCard.test.tsx
- easy-ui-react/src/SplitToggleCard/SplitToggleCard.tsx
- easy-ui-react/src/SplitToggleCard/index.ts
- Create `<SplitToggleCard />` component
> T79394 Create `<SplitToggleCard />` component

- documentation/specs/ToggleCard.md
Add spec for `ToggleCard` component
> T79393: ToggleCard spec

- documentation/specs/Spinner.md
> Spinner spec

- .changeset/great-apricots-repeat.md
- documentation/specs/ToggleCard.md
- easy-ui-react/src/Checkbox/Checkbox.test.tsx
- easy-ui-react/src/RadioGroup/RadioGroup.test.tsx
- easy-ui-react/src/SplitToggleCard/SplitToggleCard.test.tsx
- easy-ui-react/src/Toggle/Toggle.test.tsx
- easy-ui-react/src/ToggleCard/ToggleCard.mdx
- easy-ui-react/src/ToggleCard/ToggleCard.module.scss
- easy-ui-react/src/ToggleCard/ToggleCard.stories.tsx
- easy-ui-react/src/ToggleCard/ToggleCard.test.tsx
- easy-ui-react/src/ToggleCard/ToggleCard.tsx
- easy-ui-react/src/ToggleCard/index.ts
- easy-ui-react/src/utilities/test.ts
- Creates `<ToggleCard />` component
> feat: create ToggleCard component

- documentation/specs/EmptyStateCard.md
> EmptyStateCard spec

- .changeset/fair-mayflies-invite.md
- documentation/specs/EmptyStateCard.md
- easy-ui-react/src/EmptyStateCard/EmptyStateCard.mdx
- easy-ui-react/src/EmptyStateCard/EmptyStateCard.stories.tsx
- easy-ui-react/src/EmptyStateCard/EmptyStateCard.test.tsx
- easy-ui-react/src/EmptyStateCard/EmptyStateCard.tsx
- easy-ui-react/src/EmptyStateCard/index.ts
- easy-ui-react/src/utilities/react.ts
- Creates `EmptyStateCard` component
> T79384 feat: create EmptyStateCard component

- .changeset/pretty-seals-flow.md
- documentation/specs/DataGrid.md
- easy-ui-react/src/DataGrid/DataGrid.mdx
- easy-ui-react/src/DataGrid/DataGrid.stories.tsx
- easy-ui-react/src/DataGrid/DataGrid.test.tsx
- easy-ui-react/src/DataGrid/Table.tsx
- easy-ui-react/src/DataGrid/types.d.ts
> Supports DataGrid loading state

- documentation/specs/Pagination.md
> Pagination spec

- .changeset/friendly-planets-worry.md
- documentation/specs/Pagination.md
- easy-ui-react/src/Pagination/Pagination.mdx
- easy-ui-react/src/Pagination/Pagination.module.scss
- easy-ui-react/src/Pagination/Pagination.stories.tsx
- easy-ui-react/src/Pagination/Pagination.test.tsx
- easy-ui-react/src/Pagination/Pagination.tsx
- easy-ui-react/src/Pagination/PaginationButton.tsx
- easy-ui-react/src/Pagination/PaginationDropdown.tsx
- easy-ui-react/src/Pagination/index.ts
> feat: add Pagination component

- .changeset/modern-guests-bake.md
- easy-ui-react/src/Button/Button.mdx
- easy-ui-react/src/Button/Button.stories.tsx
- easy-ui-react/src/Button/Button.test.tsx
- easy-ui-react/src/Button/Button.tsx
- easy-ui-react/src/Button/utilities.ts
- easy-ui-react/src/DropdownButton/DropdownButton.mdx
- easy-ui-react/src/DropdownButton/DropdownButton.stories.tsx
- easy-ui-react/src/IconButton/IconButton.mdx
- easy-ui-react/src/IconButton/IconButton.stories.tsx
- easy-ui-react/src/utilities/storybook.tsx
- Supports warning color and outlined variant combination
> feat(Button): support warning color with  outlined variant

- documentation/specs/RadioButtonGroup.md
Provide the spec for the `<RadioButtonGroup />` to be implemented in a later PR.
> spec: RadioButtonGroup

- .changeset/empty-paws-float.md
- documentation/specs/Menu.md
- easy-ui-react/src/Menu/Menu.mdx
- easy-ui-react/src/Menu/Menu.module.scss
- easy-ui-react/src/Menu/Menu.stories.tsx
- easy-ui-react/src/Menu/Menu.test.tsx
- easy-ui-react/src/Menu/MenuItem.tsx
- easy-ui-react/src/Menu/MenuOverlay.tsx
- easy-ui-react/src/Menu/MenuSection.tsx
- easy-ui-react/src/Menu/utilities.ts
- easy-ui-react/src/utilities/react.ts
> feat: Menu supports multiple selection

- .changeset/soft-boats-clean.md
- easy-ui-icons/src/AddDiamond.json
- easy-ui-icons/src/KeyboardArrowDown.json
- easy-ui-icons/src/LabProfile.json
- easy-ui-icons/src/Replay.json
- Adds icons for more ecommerce support
> feat(icons): more icon support

- .changeset/lucky-balloons-join.md
- easy-ui-icons/src/Analytics.json
> Add analytics icon

- documentation/specs/DatePicker.md
> DatePicker spec

- .changeset/polite-hounds-mate.md
- easy-ui-react/src/RadioButtonGroup/RadioButtonGroup.module.scss
Please provide a brief summary of the changes made and why they were made.
Include any notes, screenshots, or videos that may be helpful for developers reviewing this pull request.
~- [ ] Stories accompany any component changes~
~- [ ] Unit tests accompany any component changes~
~- [ ] TSDoc is written for any API surface area~
~- [ ] Specs are up-to-date~
~- [ ] Console is free from warnings~
~- [ ] No accessibility violations are reported~
> fix(RadioButtonGroup): add focus state

- .changeset/long-bananas-push.md
- easy-ui-react/src/ForgeLayout/ForgeLayout.stories.tsx
- easy-ui-react/src/ForgeLayout/ForgeLayout.test.tsx
- easy-ui-react/src/ForgeLayout/ForgeLayout.tsx
- easy-ui-react/src/ForgeLayout/ForgeLayoutActions.module.scss
- easy-ui-react/src/ForgeLayout/ForgeLayoutActions.tsx
- Adds a button type for the actions list
> feat(ForgeLayout): add button action

- .changeset/gentle-parrots-appear.md
- easy-ui-icons/src/Edit.json
Adds the Edit icon, fixes the LocationOn icon
> Add edit icon, fix location on icon

- .changeset/thirty-squids-stare.md
- easy-ui-icons/src/EmojiObjects.json
- Add EmojiObjects icon in support of Insights related work
> feat: EmojiObjects icon

- .changeset/cold-maps-mate.md
- easy-ui-icons/src/CalendarToday.json
- easy-ui-icons/src/ForkLeft.json
- easy-ui-icons/src/Percent.json
- easy-ui-icons/src/Savings.json
- Add icons to support rules editor feature
> feat: add icons to support rules editor

- easy-ui-react/src/Card/Card.stories.tsx
- fix the Card Slat example
the Card > Slat example is one we use quite a bit in the product and it has problems with responding correctly across smaller screen sizes. for example, it wraps awkwardly. this PR fixes it to be more robust, and makes it more complex with the kebab menu that's in a lot of product contexts
*note that some css external to Easy UI are required to make this work but that's ok. Easy UI is meant to be composed*
Slat example before:
Slat example after:
> docs(Card): fix Slat example

- eslint-config-easy-ui/index.js
- eslint-config-easy-ui/package.json
- package-lock.json
- package.json
- turbo.json
> chore: upgrade Turborepo

- .changeset/angry-brooms-agree.md
- easy-ui-icons/src/AltRoute.json
> feat: add alt route icon

- easy-ui-react/src/Badge/Badge.test.tsx
- easy-ui-react/src/CodeBlock/CodeBlock.test.tsx
- easy-ui-react/vite.config.mts
- package-lock.json
- package.json
> chore: upgrade vitest

- .eslintignore
- .eslintrc.js
- easy-ui-react/src/Button/Button.tsx
- easy-ui-react/src/Button/utilities.ts
- easy-ui-react/src/Card/Card.stories.tsx
- easy-ui-react/src/Checkbox/Checkbox.stories.tsx
- easy-ui-react/src/Drawer/Drawer.stories.tsx
- easy-ui-react/src/Menu/MenuItem.tsx
- easy-ui-react/src/Menu/MenuSection.tsx
- easy-ui-react/src/Modal/Modal.stories.tsx
- easy-ui-react/src/Notification/Notification.stories.tsx
- easy-ui-react/src/ProductLayout/ProductLayout.stories.tsx
- easy-ui-react/src/SearchNav/CTAGroup.tsx
- easy-ui-react/src/SearchNav/LogoGroup.tsx
- easy-ui-react/src/Select/Select.stories.tsx
- easy-ui-react/src/Select/SelectOption.tsx
- easy-ui-react/src/Select/SelectSection.tsx
- easy-ui-react/src/Stepper/Stepper.stories.tsx
- easy-ui-react/src/TabPanels/TabPanelsItem.tsx
- easy-ui-react/src/VerticalNav/Item.tsx
- easy-ui-react/src/utilities/react.ts
- eslint-config-easy-ui/package.json
- eslint.config.mjs
- package-lock.json
- package.json
> chore: upgrade eslint

- .changeset/quick-bars-unite.md
- easy-ui-icons/src/Adjust.json
> feat: add Adjust icon

- .changeset/silent-forks-raise.md
- package-lock.json
- package.json
There were a handful of audit SVEs, including two high security ones. This just fixes those
> Bumps versions to fix audit

- .changeset/few-points-repeat.md
- easy-ui-icons/src/TrackChanges.json
> feat: add TrackChanges icon

- .changeset/itchy-kings-peel.md
- easy-ui-react/src/Badge/Badge.module.scss
- easy-ui-react/src/Badge/Badge.tsx
- easy-ui-react/src/Card/Card.tsx
- easy-ui-react/src/PlanCard/PlanCard.mdx
- easy-ui-react/src/PlanCard/PlanCard.module.scss
- easy-ui-react/src/PlanCard/PlanCard.stories.tsx
- easy-ui-react/src/PlanCard/PlanCard.test.tsx
- easy-ui-react/src/PlanCard/PlanCard.tsx
- easy-ui-react/src/PlanCard/illustrations/Building01/Building01.tsx
- easy-ui-react/src/PlanCard/illustrations/Building01/index.ts
- easy-ui-react/src/PlanCard/illustrations/Building02/Building02.tsx
- easy-ui-react/src/PlanCard/illustrations/Building02/index.ts
- easy-ui-react/src/PlanCard/illustrations/Building03/Building03.tsx
- easy-ui-react/src/PlanCard/illustrations/Building03/index.ts
- easy-ui-react/src/PlanCard/illustrations/Building04/Building04.tsx
- easy-ui-react/src/PlanCard/illustrations/Building04/index.ts
- easy-ui-react/src/PlanCard/index.ts
- easy-ui-react/src/Text/Text.module.scss
- easy-ui-react/src/Text/Text.tsx
- easy-ui-react/src/styles/_token-helpers.scss
- easy-ui-tokens/src/space/base.json
- adds `PlanCard` component
- adds `block` support to `Badge`
- adds `fontVariantNumeric` support to `Text`
- adds `negate` token helper
- ~[ ] Specs are up-to-date~
> feat: PlanCard component

- documentation/specs/HostedUILayout.md
`HostedUILayout` component spec
> HostedUILayout spec

- .changeset/huge-rings-brush.md
- easy-ui-react/src/PlanCard/PlanCard.module.scss
- used the wrong token helper for negation
> fix(PlanCard): use negate token helper

- .changeset/major-rats-sneeze.md
- documentation/specs/HostedUILayout.md
- easy-ui-icons/src/Experiment.json
- easy-ui-react/src/HostedUILayout/HostedUILayout.mdx
- easy-ui-react/src/HostedUILayout/HostedUILayout.module.scss
- easy-ui-react/src/HostedUILayout/HostedUILayout.stories.tsx
- easy-ui-react/src/HostedUILayout/HostedUILayout.test.tsx
- easy-ui-react/src/HostedUILayout/HostedUILayout.tsx
- Supports test mode for `HostedUILayout`
- Supports control over displaying EasyPost Logo for `HostedUILayout`
- Adds `Experiment` icon
> feat: support test mode and displaying logo for HostedUILayout

- .changeset/rude-peaches-glow.md
- easy-ui-icons/src/Code.json
> Add code icon

- .changeset/modern-hats-kick.md
- easy-ui-icons/Payments.json
- easy-ui-icons/src/Palette.json
Add Payments and Palette Icons
> Add Payments and Palette Icons

- .changeset/happy-radios-kiss.md
- easy-ui-icons/package.json
- easy-ui-icons/src/BarChart.json
- easy-ui-icons/src/Grade.json
- easy-ui-icons/src/Graph3.json
- easy-ui-icons/src/ReceiptLong.json
- easy-ui-icons/src/SupportAgent.json
- package-lock.json
Adds SupportAgent, ReceiptLong, Graph3, and BarChart icons. Removes the unused Grade Icon as it was removed from material-symbols
> Adds SupportAgent, ReceiptLong, Graph3, and BarChart icons

- .changeset/lovely-areas-wonder.md
- easy-ui-icons/src/InkSelection.json
- package-lock.json
- adds icon in support of feature work
- also adjusts package version in package lock
> feat: add InkSelection icon

- .changeset/big-suits-hear.md
- easy-ui-icons/src/Brightness1.json
- easy-ui-icons/src/Description.json
- easy-ui-icons/src/Manga.json
- easy-ui-icons/src/RadioButtonChecked.json
- easy-ui-icons/src/RadioButtonUnchecked.json
- easy-ui-icons/src/RemoveSelection.json
- easy-ui-icons/src/TableView.json
Adds Brightness1, Description, Manga, RadioButtonChecked, RadioButtonUnchecked, RemoveSelection, and TableView icons
> Add icons for carrier insurance

- .changeset/five-mugs-fly.md
- easy-ui-icons/src/Upload.json
> Add Upload Icon

- .changeset/ten-yaks-rhyme.md
- easy-ui-react/src/Modal/context.tsx
- package-lock.json
- Still problems with nesting modals due to state updates. Will revert hiding parent for now to unblock and dive deeper into this as part of app directly
> fix(Modal): revert nesting parent hiding
